### ISSUE TITLE
Can not download graphs

### ISSUE THREAD

**Issue by brunoalr** [tudelft-atlarge/graphalytics#109]
The link to http://atlarge.ewi.tudelft.nl/graphalytics/ is broken.

**Comment by wlngai** [comment]
Our server is currently down due to an issue in the data center. Currently we are working on migrating data back from our mirror site. Our apologies for the inconvenience,  and we will provide you an update on this within a week.

**Comment by brunoalr** [comment]
Thanks for the answer! Hope the issue is solved soon.

**Comment by brunoalr** [comment]
@wlngai any updates?

**Comment by brunoalr** [comment]
Now I can access the mirror 👍

**Comment by wlngai** [comment]
Thanks for reporting the issue. All dataset should be made accessible by end of today.

**Comment by sampollard** [comment]
Looks like the server is down again (at http://atlarge.ewi.tudelft.nl/graphalytics/)
