### ISSUE TITLE
Dataset configuration

### ISSUE THREAD

**Issue by mihaic** [tudelft-atlarge/graphalytics#20]

**Comment by thegeman** [comment]
@mihaic, with my latest PR (#31) we now have four real-world graphs:

* Amazon
* WikiTalk
* Citation
* Friendster

Do we want to add any others for now? I recall some smaller graphs from the GTA that have been used in the past.

**Comment by mihaic** [comment]
We should also have GTA-T5, KGS:
http://gta.st.ewi.tudelft.nl/datasets/GTA-T5

**Comment by mihaic** [comment]
@thegeman, will you please copy kgs.txt to atlarge:/data/graphs and describe the processing you did for obtaining it in the README there?

**Comment by thegeman** [comment]
@mihaic, do you agree with the current contents of the README?

**Comment by mihaic** [comment]
I agree.
