### ISSUE TITLE
Check output directory before running benchmark

### ISSUE THREAD

**Issue by mihaic** [tudelft-atlarge/graphalytics#61]
It's a waste of time to run the benchmark and see this at the end:
> [main] ERROR nl.tudelft.graphalytics.Graphalytics - Failed to write report: 
> java.io.IOException: Output directory of report is non-empty: "neo4j-report".

**Comment by thegeman** [comment]
The report is written to a temporary directory and then moved to its final location. If the target directory already exists, the output is still available in `/tmp`. Just checking before even running the benchmark is not a great solution either; what if you want to run multiple benchmarks on multiple Hadoop deployments?

I would propose the following: include a timestamp in the directory name. "Claim" the directory by creating an empty report directory before running any algorithms. Conflicts are unlikely, but can be resolved by appending `-1`, `-2`, etc. Do you agree?

**Comment by mihaic** [comment]
I agree.
