### ISSUE TITLE
graph files are not accessible. please provide a mirror

### ISSUE THREAD

**Issue by fadishei** [tudelft-atlarge/graphalytics#76]
Hello

I should have reported this problem to an administrator, but I did not find any contact on the project page nor on the github space. The server at atlarge.ewi.tudelft.nl which hosts graph files is down for several days. I would appreciate if you resolve the server issue or provide a secondary mirror for accessing those files.

Best regards,
Fadishei

**Comment by thegeman** [comment]
Hi Fadishei,

Unfortunately, the server hosting our datasets is currently in maintenance. Please note that our server only hosts publicly available graphs (taken from SNAP, the Game Trace Archive, and generated with https://github.com/ldbc/ldbc_snb_datagen) in a format that is consistent with Graphalytics. If you are interested in running Graphalytics, please send me an email (t.m.hegeman@student.tudelft.nl) and I will see what I can help you with until our server is back online.

With best regards,

Tim Hegeman
